---
- import_playbook: kernel_update.yml
  tags: kernel_update
- import_playbook: rocm_install.yml
  tags: rocm_install
- import_playbook: network_assign.yml
  tags: network_assign
- import_playbook: k3s_deploy.yml
  tags: k3s_deploy
- import_playbook: longhorn_deploy.yml
  tags: longhorn_deploy
- import_playbook: aws_route_deploy.yml
  tags: aws_route_deploy
- import_playbook: common_deploy.yml
  tags: common_deploy
- import_playbook: gpu_plugin_deploy.yml
  tags: gpu_plugin_deploy
- import_playbook: k3s_initial_deploy.yml
  tags: k3s_initial_deploy
