---
longhorn_helm_version: 1.11.0
longhorn_helm_namespace: longhorn-system
longhorn_helm_replica_count: 3
longhorn_helm_sds_network_name: "longhorn-storage-network"
longhorn_helm_sds_network_cidr: "10.31.254.0/24"
longhorn_helm_sds_interface: "enp196s0f1"
k3s_kubeconfig_path: /etc/rancher/k3s/k3s.yaml
